# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47b349e4ec6c248f6fa5af6253773f8947f7515f9d1c686d92011aeebf2ce9258bfcd95d311b5f64550eb9d37ced31e16a937a48f519b810c7a6ae928624e5a6

test:
  secret_key_base: 8e521bccfae690b659e4cdb7097facf71c0131161235e461edd8ea720a4f1c57bd7b024970baf00705792e765c4095dcf6340426a175fe4e32e72784f274b875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
